from typing import Protocol
from uuid import UUID

from .entities import Estudio


class IEstudioRepository(Protocol):
    async def get_by_id(self, entity_id: UUID) -> Estudio: ...
    async def save(self, entity: Estudio) -> None: ...
    async def delete(self, entity: Estudio) -> None: ...
    async def list_by_medico(self, medico_id: str) -> list[Estudio]: ...
