/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppReportesIndexRouteImport } from './routes/_app/reportes/index'
import { Route as AppPacientesIndexRouteImport } from './routes/_app/pacientes/index'
import { Route as AppEstudiosIndexRouteImport } from './routes/_app/estudios/index'
import { Route as AppReportesEstudioIdRouteImport } from './routes/_app/reportes/$estudioId'
import { Route as AppPacientesNuevoRouteImport } from './routes/_app/pacientes/nuevo'
import { Route as AppPacientesPacienteIdRouteImport } from './routes/_app/pacientes/$pacienteId'
import { Route as AppEstudiosNuevoRouteImport } from './routes/_app/estudios/nuevo'
import { Route as AppEstudiosEstudioIdRouteImport } from './routes/_app/estudios/$estudioId'
import { Route as AppAnalisisEstudioIdRouteImport } from './routes/_app/analisis/$estudioId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesIndexRoute = AppReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudiosIndexRoute = AppEstudiosIndexRouteImport.update({
  id: '/estudios/',
  path: '/estudios/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesEstudioIdRoute = AppReportesEstudioIdRouteImport.update({
  id: '/reportes/$estudioId',
  path: '/reportes/$estudioId',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesNuevoRoute = AppPacientesNuevoRouteImport.update({
  id: '/pacientes/nuevo',
  path: '/pacientes/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesPacienteIdRoute = AppPacientesPacienteIdRouteImport.update({
  id: '/pacientes/$pacienteId',
  path: '/pacientes/$pacienteId',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudiosNuevoRoute = AppEstudiosNuevoRouteImport.update({
  id: '/estudios/nuevo',
  path: '/estudios/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudiosEstudioIdRoute = AppEstudiosEstudioIdRouteImport.update({
  id: '/estudios/$estudioId',
  path: '/estudios/$estudioId',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalisisEstudioIdRoute = AppAnalisisEstudioIdRouteImport.update({
  id: '/analisis/$estudioId',
  path: '/analisis/$estudioId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/analisis/$estudioId': typeof AppAnalisisEstudioIdRoute
  '/estudios/$estudioId': typeof AppEstudiosEstudioIdRoute
  '/estudios/nuevo': typeof AppEstudiosNuevoRoute
  '/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
  '/pacientes/nuevo': typeof AppPacientesNuevoRoute
  '/reportes/$estudioId': typeof AppReportesEstudioIdRoute
  '/estudios/': typeof AppEstudiosIndexRoute
  '/pacientes/': typeof AppPacientesIndexRoute
  '/reportes/': typeof AppReportesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/analisis/$estudioId': typeof AppAnalisisEstudioIdRoute
  '/estudios/$estudioId': typeof AppEstudiosEstudioIdRoute
  '/estudios/nuevo': typeof AppEstudiosNuevoRoute
  '/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
  '/pacientes/nuevo': typeof AppPacientesNuevoRoute
  '/reportes/$estudioId': typeof AppReportesEstudioIdRoute
  '/estudios': typeof AppEstudiosIndexRoute
  '/pacientes': typeof AppPacientesIndexRoute
  '/reportes': typeof AppReportesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/analisis/$estudioId': typeof AppAnalisisEstudioIdRoute
  '/_app/estudios/$estudioId': typeof AppEstudiosEstudioIdRoute
  '/_app/estudios/nuevo': typeof AppEstudiosNuevoRoute
  '/_app/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
  '/_app/pacientes/nuevo': typeof AppPacientesNuevoRoute
  '/_app/reportes/$estudioId': typeof AppReportesEstudioIdRoute
  '/_app/estudios/': typeof AppEstudiosIndexRoute
  '/_app/pacientes/': typeof AppPacientesIndexRoute
  '/_app/reportes/': typeof AppReportesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/analisis/$estudioId'
    | '/estudios/$estudioId'
    | '/estudios/nuevo'
    | '/pacientes/$pacienteId'
    | '/pacientes/nuevo'
    | '/reportes/$estudioId'
    | '/estudios/'
    | '/pacientes/'
    | '/reportes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/analisis/$estudioId'
    | '/estudios/$estudioId'
    | '/estudios/nuevo'
    | '/pacientes/$pacienteId'
    | '/pacientes/nuevo'
    | '/reportes/$estudioId'
    | '/estudios'
    | '/pacientes'
    | '/reportes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/analisis/$estudioId'
    | '/_app/estudios/$estudioId'
    | '/_app/estudios/nuevo'
    | '/_app/pacientes/$pacienteId'
    | '/_app/pacientes/nuevo'
    | '/_app/reportes/$estudioId'
    | '/_app/estudios/'
    | '/_app/pacientes/'
    | '/_app/reportes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes/': {
      id: '/_app/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof AppReportesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/': {
      id: '/_app/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudios/': {
      id: '/_app/estudios/'
      path: '/estudios'
      fullPath: '/estudios/'
      preLoaderRoute: typeof AppEstudiosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes/$estudioId': {
      id: '/_app/reportes/$estudioId'
      path: '/reportes/$estudioId'
      fullPath: '/reportes/$estudioId'
      preLoaderRoute: typeof AppReportesEstudioIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/nuevo': {
      id: '/_app/pacientes/nuevo'
      path: '/pacientes/nuevo'
      fullPath: '/pacientes/nuevo'
      preLoaderRoute: typeof AppPacientesNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$pacienteId': {
      id: '/_app/pacientes/$pacienteId'
      path: '/pacientes/$pacienteId'
      fullPath: '/pacientes/$pacienteId'
      preLoaderRoute: typeof AppPacientesPacienteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudios/nuevo': {
      id: '/_app/estudios/nuevo'
      path: '/estudios/nuevo'
      fullPath: '/estudios/nuevo'
      preLoaderRoute: typeof AppEstudiosNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudios/$estudioId': {
      id: '/_app/estudios/$estudioId'
      path: '/estudios/$estudioId'
      fullPath: '/estudios/$estudioId'
      preLoaderRoute: typeof AppEstudiosEstudioIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analisis/$estudioId': {
      id: '/_app/analisis/$estudioId'
      path: '/analisis/$estudioId'
      fullPath: '/analisis/$estudioId'
      preLoaderRoute: typeof AppAnalisisEstudioIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAnalisisEstudioIdRoute: typeof AppAnalisisEstudioIdRoute
  AppEstudiosEstudioIdRoute: typeof AppEstudiosEstudioIdRoute
  AppEstudiosNuevoRoute: typeof AppEstudiosNuevoRoute
  AppPacientesPacienteIdRoute: typeof AppPacientesPacienteIdRoute
  AppPacientesNuevoRoute: typeof AppPacientesNuevoRoute
  AppReportesEstudioIdRoute: typeof AppReportesEstudioIdRoute
  AppEstudiosIndexRoute: typeof AppEstudiosIndexRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
  AppReportesIndexRoute: typeof AppReportesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAnalisisEstudioIdRoute: AppAnalisisEstudioIdRoute,
  AppEstudiosEstudioIdRoute: AppEstudiosEstudioIdRoute,
  AppEstudiosNuevoRoute: AppEstudiosNuevoRoute,
  AppPacientesPacienteIdRoute: AppPacientesPacienteIdRoute,
  AppPacientesNuevoRoute: AppPacientesNuevoRoute,
  AppReportesEstudioIdRoute: AppReportesEstudioIdRoute,
  AppEstudiosIndexRoute: AppEstudiosIndexRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
  AppReportesIndexRoute: AppReportesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
