"""multi_imagen_y_ollama

Revision ID: 8f9937a98d55
Revises: ae021eb48e4b
Create Date: 2026-06-06 20:22:30.385162

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f9937a98d55'
down_revision: str | Sequence[str] | None = 'ae021eb48e4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('imagenes_paths', sa.JSON(), nullable=False))
    op.add_column('analisis', sa.Column('informe_avanzado_ia', sa.Text(), nullable=True))
    op.alter_column('analisis', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('analisis', 'imagen_path')
    op.add_column('estudios', sa.Column('imagenes_paths', sa.JSON(), nullable=False))
    op.alter_column('estudios', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('estudios', 'imagen_path')
    op.alter_column('pacientes', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reportes', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('usuarios', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reportes', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('pacientes', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('estudios', sa.Column('imagen_path', sa.VARCHAR(), nullable=False))
    op.alter_column('estudios', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('estudios', 'imagenes_paths')
    op.add_column('analisis', sa.Column('imagen_path', sa.VARCHAR(), nullable=False))
    op.alter_column('analisis', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('analisis', 'informe_avanzado_ia')
    op.drop_column('analisis', 'imagenes_paths')
    # ### end Alembic commands ###
