"""initial migration

Revision ID: ae021eb48e4b
Revises: 
Create Date: 2026-06-06 16:24:23.148044

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae021eb48e4b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis',
    sa.Column('estudio_id', sa.String(), nullable=False),
    sa.Column('imagen_path', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('nivel_riesgo', sa.String(), nullable=False),
    sa.Column('hallazgos_json', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_estudio_id'), 'analisis', ['estudio_id'], unique=True)
    op.create_table('estudios',
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('imagen_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('medico_id', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudios_medico_id'), 'estudios', ['medico_id'], unique=False)
    op.create_index(op.f('ix_estudios_paciente_id'), 'estudios', ['paciente_id'], unique=False)
    op.create_table('pacientes',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=50), nullable=False),
    sa.Column('documento_identidad', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_documento_identidad'), 'pacientes', ['documento_identidad'], unique=True)
    op.create_table('reportes',
    sa.Column('estudio_id', sa.String(), nullable=False),
    sa.Column('analisis_id', sa.String(), nullable=False),
    sa.Column('nivel_riesgo', sa.String(), nullable=False),
    sa.Column('total_hallazgos', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_estudio_id'), 'reportes', ['estudio_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_reportes_estudio_id'), table_name='reportes')
    op.drop_table('reportes')
    op.drop_index(op.f('ix_pacientes_documento_identidad'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_estudios_paciente_id'), table_name='estudios')
    op.drop_index(op.f('ix_estudios_medico_id'), table_name='estudios')
    op.drop_table('estudios')
    op.drop_index(op.f('ix_analisis_estudio_id'), table_name='analisis')
    op.drop_table('analisis')
    # ### end Alembic commands ###
