from typing import Protocol
from uuid import UUID

from .entities import Paciente


class IPacienteRepository(Protocol):
    async def get_by_id(self, entity_id: UUID) -> Paciente: ...
    async def get_by_documento(self, documento_identidad: str) -> Paciente | None: ...
    async def get_all(self) -> list[Paciente]: ...
    async def save(self, entity: Paciente) -> None: ...
    async def delete(self, entity: Paciente) -> None: ...
